force-app/main/default/objects/Product_Review__c/Product_Review__c.object-meta.xml
<CustomObject>
    <label>Customer Comment</label>
    <nameField>
        <displayFormat>REV-{000000}</displayFormat>
        <label>Customer Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Review__c/fields/Prediction_Result__c.field-meta.xml
<CustomField>
    <fullName>Prediction_Result__c</fullName>
    <label>Prediction Result</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Review__c/fields/Response_Time_ms__c.field-meta.xml
<CustomField>
    <fullName>Response_Time_ms__c</fullName>
    <label>Response Time (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Review__c/fields/Sentiment_Score__c.field-meta.xml
<CustomField>
    <fullName>Sentiment_Score__c</fullName>
    <label>Raw Sentiment Score</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductReviewQueueable.cls
public with sharing class ProductReviewQueueable implements Queueable{
    private String reviewID;
    private String reviewData;

    public ProductReviewQueueable (String id, String data){
        this.reviewID=id;
        this.reviewData=data;
    }

    public void execute(QueueableContext context) {

        
        Long startTime = DateTime.now().getTime();
        
        String Jsonpayload = '{"sentimentsmessage": "'+reviewData+'"}';

        functions.Function myFunction = functions.Function.get('TDX_Demo.sentiment');
        functions.FunctionInvocation invocation = myFunction.invoke(Jsonpayload);
        String jsonResponse = invocation.getResponse();
        Long endTime = DateTime.now().getTime();
        Long milliseconds = endTime - startTime;
        System.debug(reviewID);
        jsonResponse=jsonResponse.replace('"','');
        Product_Review__c review = new Product_Review__c(Id = reviewId,
        Prediction_Result__c = jsonResponse,Sentiment_Score__c=Decimal.valueOf(jsonResponse), Response_Time_ms__c = milliseconds);
        update review;  
    }
}